spring:
  datasource:
    url: jdbc:h2:mem:messagesdb
    initialization-mode: always
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2console
      enabled: true
      settings:
        web-allow-others: true
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: accidentsDb
