management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,logfile,metrics,info,prometheus"
spring:
  data:
    mongodb:
      uri: mongodb://library-mongo
      database: ${DB_NAME}